name       : clutter-gtk
version    : 1.8.2
release    : 13
source     :
    - https://download.gnome.org/sources/clutter-gtk/1.8/clutter-gtk-1.8.2.tar.xz : da27d486325490ad3f65d2abf9413aeb8b4a8f7b559e4b2f73567a5344a26b94
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : Clutter GTK+ API
description: |
    Clutter GTK+ API
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
setup      : |
    %configure --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
