name       : clutter-gtk
version    : 1.8.0
release    : 10
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/clutter-gtk/1.8/clutter-gtk-1.8.0.tar.xz : 742ef9d68ece36cbb1b2e1a4a6fbdad932f6645360be7e6de75abbb140dfbf1d
license    :
    - LGPL-2.0
summary    : Clutter GTK+ API
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
description: |
    Clutter GTK+ API
setup      : |
    %configure --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
