name        : clutter-gtk
version     : 1.6.6
release     : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/clutter-gtk/1.6/clutter-gtk-1.6.6.tar.xz : 9440a68600f58d00fe0af35383738943e8ead9907f4cf507a102d96822434a28
license     :
    - LGPL-2.0
summary     : Clutter GTK+ API
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-1.0)
description : |
    Clutter GTK+ API
setup      : |
    %configure --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
