name       : clutter-gtk
version    : 1.8.4
release    : 23
source     :
    - https://download.gnome.org/sources/clutter-gtk/1.8/clutter-gtk-1.8.4.tar.xz : 521493ec038973c77edcb8bc5eac23eed41645117894aaee7300b2487cb42b06
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Clutter GTK+ API
description: |
    Clutter GTK+ API
builddeps  :
    - pkgconfig(clutter-1.0)
setup      : |
    %configure --disable-static --enable-introspection
build      : |
    %make
install    : |
    %make_install
